### ISSUE TITLE
Is it helping us to have a dedicated util.js file?

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#10]
https://github.com/fueled-io/bigcommerce-datalayer/blob/main/src/utils.js

I understand the value in splitting out the javascript for all events up until /checkout, from the javascript that listens for mutations on the checkout screen.

But does the current file structure in /src make sense?

Since this is an open source project, let's take a little time to think this through.

**Comment by vladgrigacodeart** [comment]
Do you think we have to combine all files into one?

**Comment by seanberto** [comment]
I think that would be reasonable - particularly if the code is well documented, @vladgrigacodeart.
