### ISSUE TITLE
Make sure there are strong inline code comments

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#21]
A very common challenge with dataLayer implementations and other tracking scripts on eCommerce websites is that website owners can’t figure out how the payload values were calculated. Each event attribute in the dataLayer javascript should be accompanied with a code comment, describing how the value was generated. These code comments should appear in the compiled dataLayer javascript object.

**Comment by boodavia** [comment]
Each function and step is described and additional details are often noted.
