### ISSUE TITLE
Confirm the dataLayer's javascript scope

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#22]
The dataLayer object should be available to Google Tag Manager, as well as other attribution scripts loaded on the page, including Segment’s Analytics.js library.

To test this, please:

* Confirm that the dataLayer is visible to a Google Tag Manager instance
* Confirm that the dataLayer can be wrapped with a Google Analytics v4 gtag and push events to GA (without leveraging GTM)
* Confirm that Segment's Analytics.js library can listen for dataLayer events and push them into a Segment source.

**Comment by boodavia** [comment]
Works as intended in my GTM and Segment sandboxes
