### ISSUE TITLE
Confirm that Visitor identification array is included in event payloads

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#24]
**Visitor identification:**

Note: Google Analytics frowns on tracking Personally Identifiable Information (PII). However, we do want to expose shopper profile data to the dataLayer, for use by other attribution and tracking scripts. In addition to the eCommerce array that's part of the event object, please include a “Shopper” array. This should be populated if we have an authenticated user on the site.

Example:

```
"shopper": {
    "customer_id": "27", 
    "email": "sean.larkin@notarealdomain.com", 
    "first_name": "Sean",
    "last_name": "Larkin",
},
```

**Comment by boodavia** [comment]
Made some tweaks to getShopper.
