### ISSUE TITLE
Build file names

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#5]
Right now, we're building into:

`filename: 'bundle.min.js',
`

We should build a minimized and non-minimized version into:

`filename: 'dataLayer.js',
`

and

`filename: 'dataLayer.min.js',
`

respectively.

**Comment by vladgrigacodeart** [comment]
Fixed

**Comment by seanberto** [comment]
Please link to PR so that this ticket automatically closes when complete, @vladgrigacodeart. TY in advance!!
