### ISSUE TITLE
Why are we calling Yotpo Schema definitions for this dataLayer?

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#6]
![Image 2021-11-06 at 3 53 45 PM](https://user-images.githubusercontent.com/109322/140624924-7efd13da-2ae2-48e4-b1b3-3bf75e809699.jpg)

**Comment by seanberto** [comment]
@vladgrigacodeart - I'm not sure why we'd want any schema to build into the production version of the dataLayer. It adds weight and potentially extraneous code. This is for testing, right? Could you connect with Eddie on this?

**Comment by vladgrigacodeart** [comment]
I've discussed with Eddie and I think we could run into two ways
1) Just remove the ajv
2) Make 3 different entry points for Prod, Dev, and Test config
@seanberto what do you think about that?

**Comment by seanberto** [comment]
I think Option #2 makes the most sense.

**Comment by vladgrigacodeart** [comment]
Done
