### ISSUE TITLE
Are we clearing the dataLayer?

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#7]
Does the following code get called, since it's not included in the functions loaded in **index.js**?

```
if (!window.dataLayer) window.dataLayer = [];
dataLayer.push({ ecommerce: null }); // Clear the previous ecommerce object.
```

![Image 2021-11-06 at 3 59 48 PM](https://user-images.githubusercontent.com/109322/140625022-8ece6035-cf63-479f-ae63-32de825ed8df.jpg)

**Comment by vladgrigacodeart** [comment]
Fixed
