### ISSUE TITLE
Are we using the same value for Product "Price" throughout dataLayer?

### ISSUE THREAD

**Issue by seanberto** [fueled-io/bigcommerce-datalayer#8]
In [bigCommerceDataLayer.js](https://github.com/fueled-io/bigcommerce-datalayer/blob/main/src/bigCommerceDataLayer.js), we define:

`price: item.price.without_tax.value,
`

However, in [checkout-started.js](https://github.com/fueled-io/bigcommerce-datalayer/blob/main/src/checkout-started.js), we define:

`price: product.salePrice,
`

Are these going to return the same values?

**Comment by vladgrigacodeart** [comment]
Yep, it's just because `product.salePrice` takes from CheckoutPage

**Comment by seanberto** [comment]
Got it! Could you please document this inline in the code?

**Comment by vladgrigacodeart** [comment]
Done
